# Generated by Django 3.2.2 on 2021-05-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prid', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=500)),
                ('original_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('Current_price', models.IntegerField()),
                ('popular_page', models.BooleanField(blank=True, default=False, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('size_available', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='', max_length=256)),
                ('Description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='image/')),
            ],
        ),
    ]
