# Generated by Django 3.2.2 on 2021-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='Intial_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='popular_page',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_display',
            field=models.CharField(choices=[('All', 'All'), ('New_Arrival', 'New_Arrival'), ('On_Sale', 'On_Sale'), ('Upcoming_product', 'Upcoming_product')], default='', max_length=256),
        ),
    ]
