# Generated by Django 3.2.2 on 2021-05-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210511_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_available',
            field=models.CharField(default='', max_length=256),
        ),
    ]
