# Generated by Django 3.1.5 on 2021-05-15 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_product_image4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='name',
        ),
        migrations.AddField(
            model_name='checkout',
            name='add_info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='checkout',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='checkout',
            name='fname',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AddField(
            model_name='checkout',
            name='lname',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='check_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
