# Generated by Django 3.2.2 on 2021-05-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210515_1738'),
        ('app', '0009_product_rating'),
    ]

    operations = [
    ]
