# Generated by Django 3.2.2 on 2021-05-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_0009_auto_20210515_1738_0009_product_rating'),
        ('app', '0011_wishlist'),
    ]

    operations = [
    ]
