# Generated by Django 3.1.5 on 2021-05-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='add_info',
            new_name='Additional_information',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='fname',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='lname',
            new_name='Last_Name',
        ),
    ]
