# Generated by Django 3.2.2 on 2021-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20210516_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.CharField(choices=[('in_stock', 'in_stock'), ('out_of_stock', 'out_of_stock'), ('currently_unavailable', 'currently_unavailable')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_available',
            field=models.CharField(default='', help_text='Please enter your name...', max_length=256),
        ),
    ]
