# Generated by Django 3.2.2 on 2021-05-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210517_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=90)),
                ('our_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_display',
            field=models.CharField(choices=[('All', 'All'), ('New_Arrival', 'New_Arrival'), ('On_Sale', 'On_Sale'), ('Upcoming_product', 'Upcoming_product')], default='All', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Jeans', 'Jeans'), ('T-shirts', 'T-shirts'), ('Chino', 'Chino'), ('Pants', 'Pants'), ('Trousers', 'Trousers'), ('Shirts', 'Shirts'), ('Winters', 'Winters'), ('Shorts', 'Shorts'), ('Socks', 'Socks'), ('Belt', 'Belt'), ('Wallet', 'Wallet'), ('Shoes', 'Shoes'), ('Mask', 'Mask'), ('other_accessories', 'other_accessories')], default='other_accessories', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.CharField(choices=[('in_stock', 'in_stock'), ('out_of_stock', 'out_of_stock'), ('currently_unavailable', 'currently_unavailable')], default='currently_unavailable', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_class',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Both', 'Both')], default='Men', max_length=256),
        ),
    ]
