# Generated by Django 3.2.2 on 2021-05-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210517_1444'),
        ('app', '0016_auto_20210517_1351'),
    ]

    operations = [
    ]
