# Generated by Django 3.1.5 on 2021-05-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_0012_auto_20210517_1444_0016_auto_20210517_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90)),
                ('email', models.CharField(default='', max_length=90)),
                ('subject', models.CharField(default='', max_length=90)),
                ('additional_information', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
