# Generated by Django 3.2.2 on 2021-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
