# Generated by Django 3.1.5 on 2021-05-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='First_Name',
            field=models.CharField(max_length=90),
        ),
    ]
