# Generated by Django 3.1.5 on 2021-05-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210520_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Delivered', 'Delivered')], default='Received', max_length=200),
        ),
    ]
