# Generated by Django 3.1.5 on 2021-05-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
